parameters:
  instagram_basic_display_api:
    token: 'IGQVJXTEtWNWRfQmsyVGMyVTBJQXJMclBhME5mUjNCRkxYdHROQkstU0NZAZAzhVUW5PZAHRWcExKQ2RfWnN1VUhwaDhteWxMUTdXOHBUQ050bjFuTmhVWFRvM1RabWZAtVmdWYlNkZA184MkZAqcjVfbC1GaQZDZD'
